export interface PaysSeed {
  code: string;
  label: string;
  /** Indicatif téléphonique sans le `+`. */
  indicatif: string;
  position: number;
}

// Les quinze premiers sont les pays de forte diaspora sénégalaise : ils sortent
// en tête du sélecteur, le reste suit par ordre alphabétique.
// Liste ISO 3166-1 alpha-2 + libellés FR (i18n-iso-countries) croisée avec les
// indicatifs de libphonenumber-js, figée ici : aucun des deux n'est appelé à
// l'exécution. Les sept territoires ISO sans indicatif (Antarctique, Bouvet,
// TAAF, Heard-et-MacDonald, Pitcairn, Géorgie du Sud, îles mineures des
// États-Unis) sont écartés : personne n'y réside.
const PAYS_ORDONNES: readonly [string, string, string][] = [
  ['FR', 'France', '33'],
  ['IT', 'Italie', '39'],
  ['ES', 'Espagne', '34'],
  ['US', 'États-Unis', '1'],
  ['GM', 'Gambie', '220'],
  ['MR', 'Mauritanie', '222'],
  ['ML', 'Mali', '223'],
  ['CI', 'Côte d’Ivoire', '225'],
  ['MA', 'Maroc', '212'],
  ['GA', 'Gabon', '241'],
  ['DE', 'Allemagne', '49'],
  ['BE', 'Belgique', '32'],
  ['CA', 'Canada', '1'],
  ['PT', 'Portugal', '351'],
  ['SA', 'Arabie saoudite', '966'],
  ['AF', 'Afghanistan', '93'],
  ['ZA', 'Afrique du Sud', '27'],
  ['AX', 'Åland', '358'],
  ['AL', 'Albanie', '355'],
  ['DZ', 'Algérie', '213'],
  ['AD', 'Andorre', '376'],
  ['AO', 'Angola', '244'],
  ['AI', 'Anguilla', '1'],
  ['AG', 'Antigua-et-Barbuda', '1'],
  ['AR', 'Argentine', '54'],
  ['AM', 'Arménie', '374'],
  ['AW', 'Aruba', '297'],
  ['AU', 'Australie', '61'],
  ['AT', 'Autriche', '43'],
  ['AZ', 'Azerbaïdjan', '994'],
  ['BS', 'Bahamas', '1'],
  ['BH', 'Bahreïn', '973'],
  ['BD', 'Bangladesh', '880'],
  ['BB', 'Barbade', '1'],
  ['BZ', 'Belize', '501'],
  ['BJ', 'Bénin', '229'],
  ['BM', 'Bermudes', '1'],
  ['BT', 'Bhoutan', '975'],
  ['BY', 'Biélorussie', '375'],
  ['BO', 'Bolivie', '591'],
  ['BQ', 'Bonaire, Saint-Eustache et Saba', '599'],
  ['BA', 'Bosnie-Herzégovine', '387'],
  ['BW', 'Botswana', '267'],
  ['BR', 'Brésil', '55'],
  ['BN', 'Brunei Darussalam', '673'],
  ['BG', 'Bulgarie', '359'],
  ['BF', 'Burkina Faso', '226'],
  ['BI', 'Burundi', '257'],
  ['KH', 'Cambodge', '855'],
  ['CM', 'Cameroun', '237'],
  ['CV', 'Cap-Vert', '238'],
  ['CL', 'Chili', '56'],
  ['CN', 'Chine', '86'],
  ['CY', 'Chypre', '357'],
  ['CO', 'Colombie', '57'],
  ['KM', 'Comores', '269'],
  ['KP', 'Corée du Nord', '850'],
  ['KR', 'Corée du Sud', '82'],
  ['CR', 'Costa Rica', '506'],
  ['HR', 'Croatie', '385'],
  ['CU', 'Cuba', '53'],
  ['CW', 'Curaçao', '599'],
  ['DK', 'Danemark', '45'],
  ['DJ', 'Djibouti', '253'],
  ['DM', 'Dominique', '1'],
  ['EG', 'Égypte', '20'],
  ['SV', 'El Salvador', '503'],
  ['AE', 'Émirats arabes unis', '971'],
  ['EC', 'Équateur', '593'],
  ['ER', 'Érythrée', '291'],
  ['EE', 'Estonie', '372'],
  ['SZ', 'Eswatini', '268'],
  ['ET', 'Éthiopie', '251'],
  ['FJ', 'Fidji', '679'],
  ['FI', 'Finlande', '358'],
  ['GE', 'Géorgie', '995'],
  ['GH', 'Ghana', '233'],
  ['GI', 'Gibraltar', '350'],
  ['GR', 'Grèce', '30'],
  ['GD', 'Grenade', '1'],
  ['GL', 'Groenland', '299'],
  ['GP', 'Guadeloupe', '590'],
  ['GU', 'Guam', '1'],
  ['GT', 'Guatemala', '502'],
  ['GG', 'Guernesey', '44'],
  ['GN', 'Guinée', '224'],
  ['GQ', 'Guinée équatoriale', '240'],
  ['GW', 'Guinée-Bissau', '245'],
  ['GY', 'Guyana', '592'],
  ['GF', 'Guyane française', '594'],
  ['HT', 'Haïti', '509'],
  ['HN', 'Honduras', '504'],
  ['HK', 'Hong Kong', '852'],
  ['HU', 'Hongrie', '36'],
  ['CX', 'Île Christmas', '61'],
  ['IM', 'Île de Man', '44'],
  ['NF', 'Île Norfolk', '672'],
  ['KY', 'Îles Caïmans', '1'],
  ['CC', 'Îles Cocos', '61'],
  ['CK', 'Îles Cook', '682'],
  ['FO', 'Îles Féroé', '298'],
  ['FK', 'Îles Malouines', '500'],
  ['MP', 'Îles Mariannes du Nord', '1'],
  ['MH', 'Îles Marshall', '692'],
  ['SB', 'Îles Salomon', '677'],
  ['TC', 'Îles Turques-et-Caïques', '1'],
  ['VI', 'Îles Vierges américaines', '1'],
  ['VG', 'Îles Vierges britanniques', '1'],
  ['IN', 'Inde', '91'],
  ['ID', 'Indonésie', '62'],
  ['IQ', 'Irak', '964'],
  ['IR', 'Iran', '98'],
  ['IE', 'Irlande', '353'],
  ['IS', 'Islande', '354'],
  ['IL', 'Israël', '972'],
  ['JM', 'Jamaïque', '1'],
  ['JP', 'Japon', '81'],
  ['JE', 'Jersey', '44'],
  ['JO', 'Jordanie', '962'],
  ['KZ', 'Kazakhstan', '7'],
  ['KE', 'Kenya', '254'],
  ['KG', 'Kirghizistan', '996'],
  ['KI', 'Kiribati', '686'],
  ['XK', 'Kosovo', '383'],
  ['KW', 'Koweït', '965'],
  ['LA', 'Laos', '856'],
  ['LS', 'Lesotho', '266'],
  ['LV', 'Lettonie', '371'],
  ['LB', 'Liban', '961'],
  ['LR', 'Libéria', '231'],
  ['LY', 'Libye', '218'],
  ['LI', 'Liechtenstein', '423'],
  ['LT', 'Lituanie', '370'],
  ['LU', 'Luxembourg', '352'],
  ['MO', 'Macao', '853'],
  ['MK', 'Macédoine du Nord', '389'],
  ['MG', 'Madagascar', '261'],
  ['MY', 'Malaisie', '60'],
  ['MW', 'Malawi', '265'],
  ['MV', 'Maldives', '960'],
  ['MT', 'Malte', '356'],
  ['MQ', 'Martinique', '596'],
  ['MU', 'Maurice', '230'],
  ['YT', 'Mayotte', '262'],
  ['MX', 'Mexique', '52'],
  ['FM', 'Micronésie', '691'],
  ['MD', 'Moldavie', '373'],
  ['MC', 'Monaco', '377'],
  ['MN', 'Mongolie', '976'],
  ['ME', 'Monténégro', '382'],
  ['MS', 'Montserrat', '1'],
  ['MZ', 'Mozambique', '258'],
  ['MM', 'Myanmar', '95'],
  ['NA', 'Namibie', '264'],
  ['NR', 'Nauru', '674'],
  ['NP', 'Népal', '977'],
  ['NI', 'Nicaragua', '505'],
  ['NE', 'Niger', '227'],
  ['NG', 'Nigéria', '234'],
  ['NU', 'Niué', '683'],
  ['NO', 'Norvège', '47'],
  ['NC', 'Nouvelle-Calédonie', '687'],
  ['NZ', 'Nouvelle-Zélande', '64'],
  ['IO', 'Océan Indien britannique', '246'],
  ['OM', 'Oman', '968'],
  ['UG', 'Ouganda', '256'],
  ['UZ', 'Ouzbékistan', '998'],
  ['PK', 'Pakistan', '92'],
  ['PW', 'Palaos', '680'],
  ['PS', 'Palestine', '970'],
  ['PA', 'Panama', '507'],
  ['PG', 'Papouasie-Nouvelle-Guinée', '675'],
  ['PY', 'Paraguay', '595'],
  ['NL', 'Pays-Bas', '31'],
  ['PE', 'Pérou', '51'],
  ['PH', 'Philippines', '63'],
  ['PL', 'Pologne', '48'],
  ['PF', 'Polynésie française', '689'],
  ['PR', 'Porto Rico', '1'],
  ['QA', 'Qatar', '974'],
  ['CF', 'République centrafricaine', '236'],
  ['CD', 'République démocratique du Congo', '243'],
  ['DO', 'République dominicaine', '1'],
  ['CG', 'République du Congo', '242'],
  ['TZ', 'République unie de Tanzanie', '255'],
  ['RE', 'Réunion', '262'],
  ['RO', 'Roumanie', '40'],
  ['GB', 'Royaume-Uni', '44'],
  ['RU', 'Russie', '7'],
  ['RW', 'Rwanda', '250'],
  ['EH', 'Sahara occidental', '212'],
  ['BL', 'Saint-Barthélemy', '590'],
  ['KN', 'Saint-Christophe-et-Niévès', '1'],
  ['SM', 'Saint-Marin', '378'],
  ['MF', 'Saint-Martin (partie française)', '590'],
  ['SX', 'Saint-Martin (partie néerlandaise)', '1'],
  ['PM', 'Saint-Pierre-et-Miquelon', '508'],
  ['VA', 'Saint-Siège (Vatican)', '39'],
  ['VC', 'Saint-Vincent-et-les-Grenadines', '1'],
  ['SH', 'Sainte-Hélène', '290'],
  ['LC', 'Sainte-Lucie', '1'],
  ['WS', 'Samoa', '685'],
  ['AS', 'Samoa américaines', '1'],
  ['ST', 'São Tomé-et-Principe', '239'],
  ['SN', 'Sénégal', '221'],
  ['RS', 'Serbie', '381'],
  ['SC', 'Seychelles', '248'],
  ['SL', 'Sierra Leone', '232'],
  ['SG', 'Singapour', '65'],
  ['SK', 'Slovaquie', '421'],
  ['SI', 'Slovénie', '386'],
  ['SO', 'Somalie', '252'],
  ['SD', 'Soudan', '249'],
  ['SS', 'Soudan du Sud', '211'],
  ['LK', 'Sri Lanka', '94'],
  ['SE', 'Suède', '46'],
  ['CH', 'Suisse', '41'],
  ['SR', 'Suriname', '597'],
  ['SJ', 'Svalbard et Île Jan Mayen', '47'],
  ['SY', 'Syrie', '963'],
  ['TJ', 'Tadjikistan', '992'],
  ['TW', 'Taïwan', '886'],
  ['TD', 'Tchad', '235'],
  ['CZ', 'Tchéquie', '420'],
  ['TH', 'Thaïlande', '66'],
  ['TL', 'Timor-Leste', '670'],
  ['TG', 'Togo', '228'],
  ['TK', 'Tokelau', '690'],
  ['TO', 'Tonga', '676'],
  ['TT', 'Trinité-et-Tobago', '1'],
  ['TN', 'Tunisie', '216'],
  ['TM', 'Turkménistan', '993'],
  ['TR', 'Turquie', '90'],
  ['TV', 'Tuvalu', '688'],
  ['UA', 'Ukraine', '380'],
  ['UY', 'Uruguay', '598'],
  ['VU', 'Vanuatu', '678'],
  ['VE', 'Venezuela', '58'],
  ['VN', 'Vietnam', '84'],
  ['WF', 'Wallis-et-Futuna', '681'],
  ['YE', 'Yémen', '967'],
  ['ZM', 'Zambie', '260'],
  ['ZW', 'Zimbabwe', '263'],
];

export const PAYS: readonly PaysSeed[] = PAYS_ORDONNES.map(
  ([code, label, indicatif], index): PaysSeed => ({
    code,
    label,
    indicatif,
    position: index + 1,
  }),
);
