export interface ProfessionSeed {
  code: string;
  label: string;
  isTeaching: boolean;
  position: number;
}

const GROUPS = {
  direction: [
    'Directeur général',
    'Directeur administratif',
    'Directeur financier',
    'Directeur des ressources humaines',
    'Directeur des opérations',
    'Directeur de programme',
    'Gérant d’entreprise',
    'Responsable d’agence',
    'Chef de service',
    'Chef de projet',
    'Entrepreneur',
    'Consultant en management',
  ],
  education: [
    'Enseignant du préscolaire',
    'Instituteur',
    'Professeur des collèges',
    'Professeur de lycée',
    'Professeur d’université',
    'Maître de conférences',
    'Assistant universitaire',
    'Formateur professionnel',
    'Éducateur spécialisé',
    'Conseiller pédagogique',
    'Inspecteur de l’éducation',
    'Proviseur',
    'Principal de collège',
    'Directeur d’école',
    'Surveillant scolaire',
    'Bibliothécaire',
    'Documentaliste',
    'Chercheur',
    'Moniteur d’alphabétisation',
    'Maître coranique',
  ],
  sante: [
    'Médecin généraliste',
    'Médecin spécialiste',
    'Chirurgien',
    'Dentiste',
    'Pharmacien',
    'Sage-femme',
    'Infirmier',
    'Aide-soignant',
    'Technicien de laboratoire',
    'Technicien en imagerie médicale',
    'Kinésithérapeute',
    'Psychologue',
    'Nutritionniste',
    'Opticien',
    'Vétérinaire',
    'Agent de santé communautaire',
    'Secrétaire médical',
    'Ambulancier',
    'Préparateur en pharmacie',
    'Hygiéniste',
  ],
  administration: [
    'Administrateur civil',
    'Secrétaire administratif',
    'Assistant de direction',
    'Secrétaire',
    'Agent d’accueil',
    'Archiviste',
    'Comptable',
    'Aide-comptable',
    'Auditeur',
    'Contrôleur de gestion',
    'Fiscaliste',
    'Trésorier',
    'Caissier',
    'Agent de recouvrement',
    'Gestionnaire de paie',
    'Chargé des ressources humaines',
    'Juriste',
    'Avocat',
    'Notaire',
    'Huissier de justice',
    'Greffier',
    'Magistrat',
    'Agent des impôts',
    'Agent du trésor',
    'Agent de collectivité territoriale',
    'Diplomate',
  ],
  finance: [
    'Banquier',
    'Conseiller clientèle bancaire',
    'Analyste financier',
    'Chargé de crédit',
    'Gestionnaire de portefeuille',
    'Courtier en assurance',
    'Agent d’assurance',
    'Actuaire',
    'Agent de microfinance',
    'Cambiste',
    'Contrôleur bancaire',
    'Opérateur de transfert d’argent',
  ],
  numerique: [
    'Développeur web',
    'Développeur mobile',
    'Ingénieur logiciel',
    'Administrateur systèmes',
    'Administrateur réseaux',
    'Technicien informatique',
    'Technicien télécoms',
    'Analyste de données',
    'Data scientist',
    'Ingénieur cybersécurité',
    'Chef de produit numérique',
    'Designer graphique',
    'Designer UX/UI',
    'Community manager',
    'Spécialiste marketing numérique',
    'Opérateur de saisie',
    'Réparateur de téléphones',
    'Technicien fibre optique',
  ],
  ingenierie: [
    'Ingénieur civil',
    'Ingénieur électromécanicien',
    'Ingénieur électricien',
    'Ingénieur industriel',
    'Ingénieur agronome',
    'Ingénieur hydraulicien',
    'Ingénieur environnement',
    'Architecte',
    'Urbaniste',
    'Géomètre',
    'Topographe',
    'Dessinateur en bâtiment',
    'Technicien génie civil',
    'Technicien supérieur industriel',
    'Électricien bâtiment',
    'Électromécanicien',
    'Frigoriste',
    'Plombier',
    'Maçon',
    'Carreleur',
    'Peintre en bâtiment',
    'Menuisier bois',
    'Menuisier aluminium',
    'Soudeur',
    'Ferrailleur',
    'Charpentier',
    'Vitrier',
  ],
  commerce: [
    'Responsable commercial',
    'Vendeur en magasin',
    'Vendeur ambulant',
    'Commerçant',
    'Grossiste',
    'Détaillant',
    'Agent immobilier',
    'Courtier',
    'Télévendeur',
    'Chargé de clientèle',
    'Agent marketing',
    'Marchandiseur',
    'Acheteur',
    'Approvisionneur',
    'Magasinier',
    'Gestionnaire de stock',
    'Agent logistique',
    'Transitaire',
    'Déclarant en douane',
    'Agent de fret',
    'Gérant de boutique',
    'Gérant de quincaillerie',
  ],
  services: [
    'Hôtelier',
    'Réceptionniste d’hôtel',
    'Cuisinier',
    'Pâtissier',
    'Boulanger',
    'Serveur de restaurant',
    'Traiteur',
    'Restaurateur',
    'Guide touristique',
    'Agent de voyage',
    'Coiffeur',
    'Esthéticien',
    'Tailleur',
    'Couturier',
    'Blanchisseur',
    'Pressing',
    'Photographe',
    'Vidéaste',
    'Musicien',
    'Artiste plasticien',
    'Décorateur',
    'Organisateur d’événements',
    'Agent d’entretien',
    'Employé de maison',
    'Gardien',
  ],
  transport: [
    'Chauffeur de taxi',
    'Chauffeur de bus',
    'Chauffeur poids lourd',
    'Conducteur de car rapide',
    'Conducteur de moto-taxi',
    'Livreur',
    'Mécanicien automobile',
    'Mécanicien moto',
    'Électricien automobile',
    'Tôlier automobile',
    'Peintre automobile',
    'Vulcanisateur',
    'Laveur de véhicules',
    'Agent de transport',
    'Contrôleur de transport',
    'Marin',
    'Docker',
    'Pilote',
    'Personnel navigant commercial',
    'Agent aéroportuaire',
  ],
  agriculture: [
    'Agriculteur',
    'Maraîcher',
    'Horticulteur',
    'Arboriculteur',
    'Éleveur bovin',
    'Éleveur ovin',
    'Aviculteur',
    'Apiculteur',
    'Pêcheur artisanal',
    'Mareyeur',
    'Aquaculteur',
    'Ouvrier agricole',
    'Technicien agricole',
    'Conseiller agricole',
    'Exploitant forestier',
    'Pépiniériste',
    'Transformateur de produits agricoles',
    'Meunier',
    'Boucher',
    'Poissonnier',
  ],
  industrie: [
    'Opérateur de production',
    'Conducteur de machine',
    'Chef d’atelier',
    'Technicien de maintenance',
    'Responsable qualité',
    'Laborantin industriel',
    'Ouvrier agroalimentaire',
    'Ouvrier textile',
    'Imprimeur',
    'Sérigraphe',
    'Ébéniste',
    'Bijoutier',
    'Cordonnier',
    'Potier',
    'Tisserand',
    'Savonnier',
    'Transformateur de céréales',
    'Emballeur',
    'Manutentionnaire',
    'Mineur',
  ],
  securite: [
    'Militaire',
    'Gendarme',
    'Policier',
    'Sapeur-pompier',
    'Agent de sécurité',
    'Douanier',
    'Agent des eaux et forêts',
    'Agent pénitentiaire',
    'Maître-nageur',
    'Secouriste',
  ],
  communication: [
    'Journaliste',
    'Reporter',
    'Présentateur radio',
    'Présentateur télévision',
    'Animateur radio',
    'Chargé de communication',
    'Attaché de presse',
    'Rédacteur',
    'Traducteur',
    'Interprète',
    'Éditeur',
    'Libraire',
    'Technicien audiovisuel',
    'Ingénieur du son',
  ],
  social: [
    'Assistant social',
    'Animateur communautaire',
    'Agent de développement local',
    'Conseiller en emploi',
    'Responsable associatif',
    'Agent d’ONG',
    'Médiateur',
    'Sociologue',
    'Économiste',
    'Statisticien',
    'Démographe',
    'Enquêteur',
    'Agent recenseur',
    'Religieux',
  ],
} as const;

const teaching = new Set<string>(GROUPS.education);
const labels = Object.values(GROUPS).flat();

export const PROFESSIONS_SENEGAL: readonly ProfessionSeed[] = labels.map((label, index) => ({
  code: `PROF_${String(index + 1).padStart(3, '0')}`,
  label,
  isTeaching: teaching.has(label),
  position: index + 1,
}));
