-- EB-24 : WhatsApp rejoint les methodes d'enrolement.
--
-- SEULE dans sa migration : PostgreSQL refuse d'utiliser une valeur
-- d'enumeration dans la transaction qui l'ajoute.
--
-- AUCUNE ligne n'est convertie, et c'est delibere. « RDV CPI » absorbe
-- « Physique » a l'ecran, mais `call_attempts_rendez_vous_matches_method` exige
-- une date sur APPOINTMENT : par construction, aucune ligne PHYSICAL n'en porte
-- une, puisque la meme contrainte l'interdisait jusqu'ici. Les convertir
-- reviendrait a leur inventer un rendez-vous, ou a desarmer la contrainte qui
-- fait tenir EB-24. Le mot change, le fait enregistre ne change pas : les
-- libelles vivent dans `phase2-labels.ts`, ou PHYSICAL se lit « RDV CPI ».
ALTER TYPE "EnrollmentMethod" ADD VALUE 'WHATSAPP';
