import { chromium } from '@playwright/test';
const b = await chromium.launch();
const c = await b.newContext({ viewport:{width:1440,height:1000}, locale:'fr-FR' });
const p = await c.newPage();
await p.goto('http://localhost:3000/connexion');
await p.getByLabel(/identifiant|e-mail|email/i).first().fill('admin@cpi.sn');
await p.getByLabel(/mot de passe/i).first().fill('ChangeMoiEnProd2026');
await p.getByRole('button', { name: /connexion|se connecter/i }).click();
await p.waitForURL(/tableau-de-bord/); await p.waitForLoadState('networkidle'); await p.waitForTimeout(1200);
console.log('cookie avant :', await p.evaluate(() => document.cookie));
await p.getByRole('button', { name: /Réduire la navigation/i }).click();
await p.waitForTimeout(600);
console.log('cookie après :', await p.evaluate(() => document.cookie));
console.log('ctx cookies :', (await c.cookies()).map(x => `${x.name}=${x.value}`).join(' | '));
await p.reload(); await p.waitForLoadState('networkidle'); await p.waitForTimeout(1000);
console.log('cookie au rechargement :', await p.evaluate(() => document.cookie));
console.log('largeur :', await p.evaluate(() => document.querySelector('aside')?.getBoundingClientRect().width));
await b.close();
