-- ─────────────────────────────────────────────────────────────────────────────
-- Le bail d'expédition d'une notification reçoit une IDENTITÉ DE PROPRIÉTAIRE.
--
-- CE QUE LA COLONNE RÉPARE.
--
-- La prise en charge d'un envoi s'écrivait `status = SENDING`, et sa fraîcheur
-- se lisait sur `updatedAt`. Ces deux valeurs disent QU'UN processus a
-- travaillé ; elles ne disent pas LEQUEL. Un expéditeur suspendu au-delà du
-- bail, dont la notification avait été reprise par un second, se réveillait,
-- réécrivait `SENDING` (donc renouvelait le bail DU SECOND) et poursuivait ses
-- envois sur les mêmes livraisons. Les deux processus se croyaient seuls, et le
-- destinataire recevait le message en double.
--
-- Chaque prise écrit désormais un jeton neuf dans cette colonne, et toute
-- écriture d'expédition le porte dans son `where` : le processus qui ne détient
-- plus le jeton n'écrit plus rien, et cesse d'envoyer. C'est la forme déjà
-- retenue par `outbox.claim_token` côté mobile.
--
-- POURQUOI NULLABLE, ET POURQUOI SANS DÉFAUT. `NULL` est un état utile et
-- fréquent : « personne ne tient cet envoi ». Une notification qui vient d'être
-- composée le porte, et c'est ce qui la rend immédiatement prenable sans
-- attendre l'expiration d'un bail que personne n'a jamais posé. Les lignes
-- existantes prennent donc `NULL`, qui est exactement leur état réel.
--
-- AUCUN INDEX. La colonne n'est jamais un critère de recherche : elle n'apparaît
-- que dans des `where` déjà réduits à une clé primaire.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE "notifications" ADD COLUMN "dispatchClaim" TEXT;
