import {
  ActivityIcon,
  ChartColumnIcon,
  ClockIcon,
  ContactRoundIcon,
  FileSpreadsheetIcon,
  FolderOpenIcon,
  HeadsetIcon,
  HouseIcon,
  LayoutDashboardIcon,
  ListOrderedIcon,
  MegaphoneIcon,
  PhoneCallIcon,
  PhoneForwardedIcon,
  PlusCircleIcon,
  UploadIcon,
  UserPlusIcon,
  UsersIcon,
  UsersRoundIcon,
} from 'lucide-react';

import type { NavItem } from '@/lib/nav';
import { ADMIN_SEUL, BANQUE_SEULE } from '@/lib/roles';

/** L'administrateur et l'agent bancaire lisent leur propre suite d'entrées. */
export const NAV_CHUES_ADMIN: readonly NavItem[] = [
  {
    href: '/chues/statistiques',
    label: 'Tableau de bord',
    icon: LayoutDashboardIcon,
    description: 'Appels, adhésions et encaissements',
    roles: ADMIN_SEUL,
  },
  {
    href: '/chues',
    label: 'Les trois étapes',
    icon: HouseIcon,
    description: 'Qualifier, ajouter, convertir',
    roles: ADMIN_SEUL,
    secondary: true,
  },
  {
    href: '/chues/prospects',
    label: 'Prospects',
    icon: UsersIcon,
    description: 'Liste filtrable et export',
    roles: ADMIN_SEUL,
  },
  {
    href: '/chues/representants',
    label: 'Représentants',
    icon: UsersRoundIcon,
    description: 'Enseignants qui donnent les contacts',
    roles: ADMIN_SEUL,
  },
  {
    href: '/chues/campagnes',
    label: 'Tableau de bord',
    icon: MegaphoneIcon,
    description: 'Fiches exportées pour le terrain',
    roles: ADMIN_SEUL,
    hidden: true,
    onglet: '/chues/statistiques',
  },
  {
    href: '/chues/dossiers',
    label: 'Dossiers bancaires',
    icon: FolderOpenIcon,
    description: 'Dossiers déposés en banque',
    roles: ADMIN_SEUL,
  },
  {
    href: '/chues/supervision',
    label: 'Tableau de bord',
    icon: ActivityIcon,
    description: 'Activité et présence des téléconseillers',
    roles: ADMIN_SEUL,
    hidden: true,
    onglet: '/chues/statistiques',
  },
  {
    href: '/chues/rappels',
    label: 'Rappels',
    icon: ClockIcon,
    description: 'Échéances promises et retards',
    roles: ADMIN_SEUL,
    secondary: true,
  },
  {
    href: '/chues/mes-contacts',
    label: 'Mes contacts',
    icon: ContactRoundIcon,
    description: 'Les personnes que j’ai appelées',
    roles: ADMIN_SEUL,
    secondary: true,
  },
  {
    href: '/chues/suggestions',
    label: 'Contacts recommandés',
    icon: PhoneForwardedIcon,
    description: 'Numéros donnés par les représentants',
    roles: ADMIN_SEUL,
    secondary: true,
  },
  {
    href: '/chues/banque',
    label: 'Tableau de bord',
    icon: ChartColumnIcon,
    description: 'Encaissements, rejets et délais',
    roles: ADMIN_SEUL,
    hidden: true,
    onglet: '/chues/statistiques',
  },
  {
    href: '/chues/demandes-clients',
    label: 'Créations de client à valider',
    icon: UserPlusIcon,
    description: 'Créations demandées par les banques',
    roles: ADMIN_SEUL,
    secondary: true,
  },
  {
    href: '/chues/dossiers/export',
    label: 'Exporter les dossiers',
    icon: FileSpreadsheetIcon,
    description: 'Classeur Dossiers · Historique · Synthèse',
    roles: ADMIN_SEUL,
    secondary: true,
  },
  {
    href: '/chues/dossiers/etapes',
    label: 'Étapes des dossiers',
    icon: ListOrderedIcon,
    description: 'Flux de traitement',
    roles: ADMIN_SEUL,
    secondary: true,
  },
  {
    href: '/chues/appels-representants',
    label: 'Qualifier un représentant',
    icon: PhoneCallIcon,
    description: 'Première des trois étapes',
    roles: ADMIN_SEUL,
    hidden: true,
  },
  {
    href: '/chues/console',
    label: 'Convertir un prospect',
    icon: HeadsetIcon,
    description: 'Dernière des trois étapes',
    roles: ADMIN_SEUL,
    hidden: true,
  },
  {
    href: '/chues/prospects/nouveau',
    label: 'Ajouter un prospect',
    icon: PlusCircleIcon,
    description: 'Deuxième des trois étapes',
    roles: ADMIN_SEUL,
    hidden: true,
  },
  {
    href: '/chues/dossiers/nouveau',
    label: 'Nouveau dossier',
    icon: PlusCircleIcon,
    description: 'Ouverture de dossier',
    roles: ADMIN_SEUL,
    hidden: true,
  },
  {
    href: '/chues/representants/import',
    label: 'Importer des représentants',
    icon: UploadIcon,
    description: 'Classeur de représentants',
    roles: ADMIN_SEUL,
    hidden: true,
  },
  {
    href: '/chues/banque',
    label: 'Vue d’ensemble',
    icon: LayoutDashboardIcon,
    description: 'Encaissements, rejets et délais',
    roles: BANQUE_SEULE,
  },
  {
    href: '/chues/dossiers',
    label: 'Dossiers bancaires',
    icon: FolderOpenIcon,
    description: 'Dossiers déposés en banque',
    roles: BANQUE_SEULE,
  },
  {
    href: '/chues/dossiers/nouveau',
    label: 'Ouvrir un dossier',
    icon: PlusCircleIcon,
    description: 'Ouverture de dossier',
    roles: BANQUE_SEULE,
  },
  {
    // Le suivi de ses propres demandes : l'API les borne à `requestedById`.
    href: '/chues/demandes-clients',
    label: 'Mes demandes de création',
    icon: UserPlusIcon,
    description: 'Créations de client demandées',
    roles: BANQUE_SEULE,
  },
  {
    href: '/chues/dossiers/export',
    label: 'Exporter les dossiers',
    icon: FileSpreadsheetIcon,
    description: 'Classeur Dossiers · Historique · Synthèse',
    roles: BANQUE_SEULE,
    secondary: true,
  },
];
