//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:json_annotation/json_annotation.dart';

enum DashboardSource {
  @JsonValue(r'total-visites')
  totalVisites(r'total-visites'),
  @JsonValue(r'moyenne-journaliere')
  moyenneJournaliere(r'moyenne-journaliere'),
  @JsonValue(r'jour-le-plus-charge')
  jourLePlusCharge(r'jour-le-plus-charge'),
  @JsonValue(r'par-entreprise')
  parEntreprise(r'par-entreprise'),
  @JsonValue(r'par-objet')
  parObjet(r'par-objet'),
  @JsonValue(r'par-direction')
  parDirection(r'par-direction'),
  @JsonValue(r'par-destinataire')
  parDestinataire(r'par-destinataire'),
  @JsonValue(r'par-jour')
  parJour(r'par-jour'),
  @JsonValue(r'par-mois')
  parMois(r'par-mois'),
  @JsonValue(r'par-heure')
  parHeure(r'par-heure'),
  @JsonValue(r'par-jour-semaine')
  parJourSemaine(r'par-jour-semaine'),
  @JsonValue(r'par-heure-jour-semaine')
  parHeureJourSemaine(r'par-heure-jour-semaine'),
  @JsonValue(r'par-agent')
  parAgent(r'par-agent'),
  @JsonValue(r'par-entreprise-objet')
  parEntrepriseObjet(r'par-entreprise-objet'),
  @JsonValue(r'par-destinataire-direction')
  parDestinataireDirection(r'par-destinataire-direction'),
  @JsonValue(r'par-objet-mois')
  parObjetMois(r'par-objet-mois'),
  @JsonValue(r'visiteurs-recurrents')
  visiteursRecurrents(r'visiteurs-recurrents'),
  @JsonValue(r'avec-telephone')
  avecTelephone(r'avec-telephone'),
  @JsonValue(r'qualite-de-saisie')
  qualiteDeSaisie(r'qualite-de-saisie'),
  @JsonValue(r'taux-de-contact')
  tauxDeContact(r'taux-de-contact'),
  @JsonValue(r'taux-de-joignabilite-representants')
  tauxDeJoignabiliteRepresentants(r'taux-de-joignabilite-representants'),
  @JsonValue(r'taux-d-acceptation')
  tauxDAcceptation(r'taux-d-acceptation'),
  @JsonValue(r'taux-de-rappel')
  tauxDeRappel(r'taux-de-rappel'),
  @JsonValue(r'repartition-statuts-qualification')
  repartitionStatutsQualification(r'repartition-statuts-qualification'),
  @JsonValue(r'joints-non-joints')
  jointsNonJoints(r'joints-non-joints'),
  @JsonValue(r'statuts-par-famille')
  statutsParFamille(r'statuts-par-famille'),
  @JsonValue(r'joignabilite-par-creneau')
  joignabiliteParCreneau(r'joignabilite-par-creneau'),
  @JsonValue(r'taux-d-exploitation')
  tauxDExploitation(r'taux-d-exploitation'),
  @JsonValue(r'representants-par-departement')
  representantsParDepartement(r'representants-par-departement'),
  @JsonValue(r'representants-par-ief')
  representantsParIef(r'representants-par-ief'),
  @JsonValue(r'representants-jamais-appeles')
  representantsJamaisAppeles(r'representants-jamais-appeles'),
  @JsonValue(r'representants-injoignables')
  representantsInjoignables(r'representants-injoignables'),
  @JsonValue(r'taux-de-joignabilite')
  tauxDeJoignabilite(r'taux-de-joignabilite'),
  @JsonValue(r'prospects-notes')
  prospectsNotes(r'prospects-notes'),
  @JsonValue(r'adhesions')
  adhesions(r'adhesions'),
  @JsonValue(r'reste-a-appeler')
  resteAAppeler(r'reste-a-appeler'),
  @JsonValue(r'fiches-ouvertes')
  fichesOuvertes(r'fiches-ouvertes'),
  @JsonValue(r'taux-de-qualification')
  tauxDeQualification(r'taux-de-qualification'),
  @JsonValue(r'duree-moyenne-sur-la-fiche')
  dureeMoyenneSurLaFiche(r'duree-moyenne-sur-la-fiche'),
  @JsonValue(r'duree-moyenne-de-communication')
  dureeMoyenneDeCommunication(r'duree-moyenne-de-communication'),
  @JsonValue(r'appels-par-jour')
  appelsParJour(r'appels-par-jour'),
  @JsonValue(r'par-teleconseiller')
  parTeleconseiller(r'par-teleconseiller'),
  @JsonValue(r'couverture-derniere-campagne')
  couvertureDerniereCampagne(r'couverture-derniere-campagne'),
  @JsonValue(r'hors-attribution-derniere-campagne')
  horsAttributionDerniereCampagne(r'hors-attribution-derniere-campagne'),
  @JsonValue(r'encaisse')
  encaisse(r'encaisse'),
  @JsonValue(r'de-l-appel-a-l-encaissement')
  deLAppelALEncaissement(r'de-l-appel-a-l-encaissement'),
  @JsonValue(r'methodes-d-adhesion')
  methodesDAdhesion(r'methodes-d-adhesion'),
  @JsonValue(r'par-banque')
  parBanque(r'par-banque'),
  @JsonValue(r'delais-medians')
  delaisMedians(r'delais-medians'),
  @JsonValue(r'rendement-par-departement')
  rendementParDepartement(r'rendement-par-departement'),
  @JsonValue(r'enrolement-inscriptions')
  enrolementInscriptions(r'enrolement-inscriptions'),
  @JsonValue(r'enrolement-taux-rapprochement')
  enrolementTauxRapprochement(r'enrolement-taux-rapprochement'),
  @JsonValue(r'enrolement-taux-conversion')
  enrolementTauxConversion(r'enrolement-taux-conversion'),
  @JsonValue(r'enrolement-par-jour')
  enrolementParJour(r'enrolement-par-jour'),
  @JsonValue(r'enrolement-par-etape')
  enrolementParEtape(r'enrolement-par-etape'),
  @JsonValue(r'enrolement-par-teleconseiller')
  enrolementParTeleconseiller(r'enrolement-par-teleconseiller'),
  @JsonValue(r'unknown_default_open_api')
  unknownDefaultOpenApi(r'unknown_default_open_api');

  const DashboardSource(this.value);

  final String value;

  @override
  String toString() => value;
}
