import {
  ActivityIcon,
  ChartColumnIcon,
  ClockIcon,
  ContactRoundIcon,
  FileSpreadsheetIcon,
  FolderOpenIcon,
  HeadsetIcon,
  LayoutDashboardIcon,
  LibraryIcon,
  MegaphoneIcon,
  PlusCircleIcon,
  UploadIcon,
  UsersIcon,
} from 'lucide-react';

import type { NavItem } from '@/lib/nav';
import { ADMIN_SEUL, BANQUE_SEULE, ENCADREMENT, PILOTAGE, TELECONSEIL } from '@/lib/roles';

/**
 * Pas de « Contacts recommandés » ici : une suggestion est le numéro d'un tiers
 * nommé par un représentant syndical, et la notion n'existe pas hors CHUES.
 */
export const NAV_GRAND_PUBLIC: readonly NavItem[] = [
  {
    href: '/grand-public',
    label: 'Grand Public',
    icon: UsersIcon,
    description: 'Créer, retrouver et suivre les prospects',
    roles: TELECONSEIL,
  },
  {
    href: '/grand-public/console',
    label: 'Appeler les prospects',
    icon: HeadsetIcon,
    description: 'Chercher un prospect et consigner l’appel',
    roles: TELECONSEIL,
  },
  {
    href: '/grand-public/rappels',
    label: 'Rappels promis',
    icon: ClockIcon,
    description: 'Ce qu’on a promis de rappeler',
    roles: TELECONSEIL,
  },
  {
    href: '/grand-public/mes-contacts',
    label: 'Mes contacts',
    icon: ContactRoundIcon,
    description: 'Les personnes que j’ai appelées',
    roles: TELECONSEIL,
    secondary: true,
  },
  {
    href: '/grand-public/nouveau',
    label: 'Noter un prospect',
    icon: PlusCircleIcon,
    description: 'Saisie d’un prospect',
    roles: TELECONSEIL,
    secondary: true,
  },
  {
    href: '/grand-public/statistiques',
    label: 'Tableau de bord',
    icon: LayoutDashboardIcon,
    description: 'Activité et conversion',
    roles: PILOTAGE,
  },
  {
    href: '/grand-public',
    label: 'Prospects',
    icon: UsersIcon,
    description: 'Liste filtrable des prospects',
    roles: PILOTAGE,
  },
  {
    href: '/grand-public/supervision',
    label: 'Tableau de bord',
    icon: ActivityIcon,
    description: 'Activité et présence des téléconseillers',
    roles: PILOTAGE,
    hidden: true,
    onglet: '/grand-public/statistiques',
  },
  {
    href: '/grand-public/dossiers',
    label: 'Dossiers bancaires',
    icon: FolderOpenIcon,
    description: 'Dossiers déposés en banque',
    roles: ADMIN_SEUL,
  },
  {
    href: '/grand-public/rappels',
    label: 'Rappels',
    icon: ClockIcon,
    description: 'Échéances promises et retards',
    roles: PILOTAGE,
    secondary: true,
  },
  {
    href: '/grand-public/mes-contacts',
    label: 'Mes contacts',
    icon: ContactRoundIcon,
    description: 'Les personnes que j’ai appelées',
    roles: PILOTAGE,
    secondary: true,
  },
  {
    href: '/grand-public/campagnes',
    label: 'Tableau de bord',
    icon: MegaphoneIcon,
    description: 'Fiches exportées pour le terrain',
    roles: PILOTAGE,
    hidden: true,
    onglet: '/grand-public/statistiques',
  },
  {
    href: '/admin/referentiels',
    label: 'Listes de référence',
    icon: LibraryIcon,
    description: 'Départements, banques, syndicats',
    roles: ENCADREMENT,
    secondary: true,
  },
  {
    href: '/grand-public/console',
    label: 'Appeler les prospects',
    icon: HeadsetIcon,
    description: 'Chercher un prospect et consigner l’appel',
    roles: ADMIN_SEUL,
    secondary: true,
  },
  {
    href: '/grand-public/nouveau',
    label: 'Noter un prospect',
    icon: PlusCircleIcon,
    description: 'Saisie d’un prospect',
    roles: ADMIN_SEUL,
    secondary: true,
  },
  {
    href: '/grand-public/banque',
    label: 'Tableau de bord',
    icon: ChartColumnIcon,
    description: 'Encaissements, rejets et délais',
    roles: ADMIN_SEUL,
    hidden: true,
    onglet: '/grand-public/statistiques',
  },
  {
    href: '/grand-public/dossiers/export',
    label: 'Exporter les dossiers',
    icon: FileSpreadsheetIcon,
    description: 'Classeur Dossiers · Historique · Synthèse',
    roles: ADMIN_SEUL,
    secondary: true,
  },
  {
    href: '/grand-public/dossiers/nouveau',
    label: 'Nouveau dossier',
    icon: PlusCircleIcon,
    description: 'Ouverture de dossier',
    roles: ADMIN_SEUL,
    hidden: true,
  },
  {
    // L'écran de dépôt vit chez l'Admin ; le paramètre y présélectionne le
    // classeur Grand Public.
    href: '/admin/imports?kind=PROSPECTS_GRAND_PUBLIC',
    label: 'Importer des prospects',
    icon: UploadIcon,
    description: 'Classeur de prospects Grand Public',
    roles: ADMIN_SEUL,
    secondary: true,
  },
  {
    href: '/grand-public/banque',
    label: 'Vue d’ensemble',
    icon: LayoutDashboardIcon,
    description: 'Encaissements, rejets et délais',
    roles: BANQUE_SEULE,
  },
  {
    href: '/grand-public/dossiers',
    label: 'Dossiers bancaires',
    icon: FolderOpenIcon,
    description: 'Dossiers déposés en banque',
    roles: BANQUE_SEULE,
  },
  {
    href: '/grand-public/dossiers/nouveau',
    label: 'Ouvrir un dossier',
    icon: PlusCircleIcon,
    description: 'Ouverture de dossier',
    roles: BANQUE_SEULE,
  },
  {
    href: '/grand-public/dossiers/export',
    label: 'Exporter les dossiers',
    icon: FileSpreadsheetIcon,
    description: 'Classeur Dossiers · Historique · Synthèse',
    roles: BANQUE_SEULE,
    secondary: true,
  },
];
