import type { Permission } from '@/lib/types';

export const AIDE_PERMISSIONS: Record<Permission, string> = {
  'accueil.listes': 'Modifier les listes de choix du registre des visites et importer des visites.',
  'accueil.registre': 'Enregistrer les visites à l’accueil et les archiver.',
  'analytics.superviser':
    'Ouvrir les tableaux de bord de supervision : activité, entonnoir, pôle marketing.',
  'banque.administrer': 'Régler les étapes des dossiers Banque & Finance et valider les dossiers.',
  'banque.dossiers': 'Faire avancer les dossiers Banque & Finance de son portefeuille.',
  'banque.lire': 'Consulter les dossiers Banque & Finance, sans les modifier.',
  'banque.voir_tous_portefeuilles':
    'Voir les demandes Banque & Finance de tous les portefeuilles, pas seulement le sien.',
  'bases.administrer': 'Créer et supprimer les bases de démonstration.',
  'campagnes.administrer': 'Supprimer une campagne d’appels.',
  'campagnes.attributions_toutes': 'Voir qui a reçu quelle fiche dans toutes les campagnes.',
  'campagnes.gerer': 'Créer et modifier les campagnes d’appels.',
  'campagnes.superviser': 'Suivre l’avancement des campagnes d’appels.',
  'chiffres.disposer': 'Choisir les blocs du tableau de bord et leur disposition.',
  'chiffres.voir_montants': 'Afficher les montants (ventes, paiements) dans les chiffres.',
  'comptes.administrer': 'Créer, modifier et désactiver les comptes.',
  'comptes.lister': 'Voir la liste des comptes, sans les modifier.',
  'courriels.administrer': 'Régler les courriels envoyés par le CRM.',
  'donnees.voir_supprimees': 'Voir les fiches et données supprimées.',
  'enrolement.administrer': 'Suivre les inscriptions de la plateforme et régler l’enrôlement.',
  'exploitation.administrer': 'Consulter le journal d’exploitation et purger des données.',
  'exports.banque': 'Exporter les dossiers Banque & Finance.',
  'exports.globaux': 'Exporter les données de supervision (Excel global).',
  'exports.modeles': 'Télécharger les modèles de fichiers d’import.',
  'exports.prospects': 'Exporter les prospects de son portefeuille.',
  'exports.voir_tout': 'Exporter le portefeuille d’un autre téléconseiller.',
  'fiches.consigner_attribuees':
    'Enregistrer un appel sur une fiche distribuée à un autre téléconseiller. Sans elle, l’enregistrement de l’appel est refusé.',
  'fiches.forcer_transition':
    'Changer le statut d’une fiche même quand le parcours ne le permet pas.',
  'fiches.ignorer_propriete': 'Agir sur les rappels et les identifiants créés par d’autres.',
  'fiches.modifier_toutes': 'Modifier et supprimer les fiches créées par d’autres.',
  'fiches.ouvrir_attribuees': 'Ouvrir une fiche distribuée à un autre téléconseiller.',
  'fiches.parametres_reserves': 'Régler les liens, l’adresse et les destinataires CHUES.',
  'fiches.tenir': 'Lire et modifier les fiches de son propre portefeuille.',
  'fiches.voir_converties':
    'Voir aussi les fiches déjà converties dans les listes et à l’ouverture.',
  'formulaires.administrer': 'Régler les champs du formulaire de conversion.',
  'imports.administrer': 'Importer des fichiers de prospects ou de représentants.',
  'notifications.administrer': 'Envoyer des notifications et régler leur envoi.',
  'panneau.acceder': 'Se connecter au panneau. Sans elle, le compte ne peut rien ouvrir.',
  'parametres.administrer': 'Régler les objectifs et les tableaux de bord par défaut.',
  'portefeuille.voir_tout':
    'Voir les portefeuilles de tous les téléconseillers, pas seulement le sien.',
  'prospects.convertir': 'Convertir un prospect Grand Public.',
  'prospects.fusionner': 'Fusionner deux fiches en doublon.',
  'prospects.lire': 'Consulter la liste et le détail des prospects.',
  'prospects.reaffecter': 'Redistribuer des fiches de son propre portefeuille.',
  'prospects.reaffecter_tout': 'Redistribuer une fiche vers n’importe quel téléconseiller.',
  'prospects.revoir': 'Traiter une demande de révision sur une fiche.',
  'prospects.superviser': 'Régler les segments et paramètres CHUES, et requalifier une fiche.',
  'qualification.rappels': 'Reporter ou annuler ses propres rappels.',
  'referentiels.superviser': 'Modifier les listes de référence : motifs, statuts, départements.',
  'rendez_vous.suivre':
    'Noter l’issue d’un rendez-vous et la suite donnée après la rencontre (bêta).',
  'roles.administrer': 'Créer des rôles et régler leurs permissions, dont celle-ci.',
  'support.plateforme': 'Ouvrir la plateforme de support GLPI.',
  'support.signaler': 'Signaler un problème au support depuis un écran.',
  'ventes.lire': 'Consulter les ventes.',
  'visites.detruire': 'Détruire définitivement une visite archivée.',
  'visites.voir_archivees': 'Consulter les visites archivées.',
};
