import type { ProspectRow } from '@/lib/types';

/**
 * Une fiche COMPLÈTE : le codegen ajoute des colonnes, et trois tests recopiaient
 * le même objet à la main. Le typecheck cassait alors dans trois fichiers à la
 * fois pour une seule colonne ajoutée.
 */
export function prospectFixture(over: Partial<ProspectRow> & { id: string }): ProspectRow {
  return {
    nom: 'Diallo',
    prenom: 'Mamadou',
    phoneE164: '+221771234567',
    rev: 1,
    statut: 'NOUVEAU',
    projet: 'CHUES',
    champsLibres: {},
    banqueId: 'b-1',
    banqueName: 'CBAO',
    syndicatId: 's-1',
    syndicatSigle: 'SUDES',
    representantId: 'r-1',
    representantName: 'Aminata Ndiaye',
    representantPhoneE164: '+221770000000',
    departementId: 'd-1',
    departementName: 'Dakar',
    ownedByCommercialId: 'u-1',
    ownedByCommercialName: 'Fatou Sow',
    type: null,
    profession: null,
    professionId: null,
    professionIsTeaching: null,
    incomeBandId: null,
    incomeBandLabel: null,
    paymentMode: null,
    employeurId: null,
    employeur: null,
    typeContrat: null,
    ancienneteMois: null,
    lieuActivite: null,
    modeEpargne: null,
    paysResidenceId: null,
    paysResidenceLabel: null,
    villeResidence: null,
    etablissement: null,
    whatsappStatus: 'NON_DEMANDE',
    whatsappE164: null,
    whatsappNumber: null,
    relaisNom: null,
    relaisPhoneE164: null,
    journeys: [],
    dureeSystemeMois: null,
    canalProvenanceId: null,
    canalProvenanceLabel: null,
    segment: 'BDD1',
    phase2Status: 'PENDING',
    enrollmentMethod: null,
    enrollmentCapturedById: null,
    enrollmentCapturedByName: null,
    enrollmentCapturedAt: null,
    revueAt: null,
    aRevoirAt: null,
    revueById: null,
    revueByName: null,
    lastOutcome: null,
    lastComment: null,
    lastAttemptAt: null,
    callAttemptCount: 0,
    lastCallOutcome: null,
    lastCallAt: null,
    lastCallById: null,
    lastCallByName: null,
    origin: null,
    originLabel: null,
    clientCreatedAt: '2026-01-01T00:00:00.000Z',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    deletedAt: null,
    ...over,
  };
}
