export * from '@prisma/client';
export { PrismaPg } from '@prisma/adapter-pg';
export * from './seed-data/geo.js';
export * from './seed-data/ief.js';
export * from './seed-data/banques.js';
export * from './seed-data/syndicats.js';
export * from './seed-data/bank-workflow.js';
export * from './seed-data/call-outcomes.js';
export * from './seed-data/canaux-provenance.js';
export * from './segment.js';
export * from './demo/index.js';
export * from './seed-data/visites.js';
