package main

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
)

// seedFactory populates every operational area with deterministic development
// rows. It is intentionally separate from reference data and never runs in prod.
func seedFactory(ctx context.Context, tx pgx.Tx) error {
	statements := []string{
		`INSERT INTO "representants" ("id","fullName","phoneE164","departementId","createdById","clientCreatedAt","updatedAt","relationStatus","prenom","etablissement","contacte") SELECT 'dev-rep-001','Aminata Diop','+221770009001',(SELECT "id" FROM "departements" LIMIT 1),(SELECT "id" FROM "users" WHERE "email"='fixture.superviseur@cpi.sn'),now()-interval '20 days',now(),'AMBASSADEUR'::"RepresentantRelation",'Aminata','École de Dakar',true WHERE EXISTS (SELECT 1 FROM "users" WHERE "email"='fixture.superviseur@cpi.sn') ON CONFLICT DO NOTHING`,
		`INSERT INTO "prospects" ("id","nom","prenom","phoneE164","banqueId","syndicatId","representantId","createdById","clientCreatedAt","updatedAt","projet","statut","type","professionId","incomeBandId","employeurId","canalProvenanceId","paysResidenceId","villeResidence","email") SELECT 'dev-prospect-'||g,'Nom'||g,'Prénom'||g,'+221770009'||lpad(g::text,3,'0'),(SELECT "id" FROM "banques" LIMIT 1),(SELECT "id" FROM "syndicats" LIMIT 1),'dev-rep-001',(SELECT "id" FROM "users" WHERE "email"='fixture.awa@cpi.sn'),now()-make_interval(days=>g),now(),'CHUES'::"Projet",CASE WHEN g%3=0 THEN 'CONTACTE'::"ProspectStatut" ELSE 'NOUVEAU'::"ProspectStatut" END,'FONCTIONNAIRE'::"ProspectType",(SELECT "id" FROM "professions" WHERE "isTeaching" LIMIT 1),(SELECT "id" FROM "income_bands" LIMIT 1),(SELECT "id" FROM "employeurs" LIMIT 1),(SELECT "id" FROM "canaux_provenance" LIMIT 1),(SELECT "id" FROM "pays" LIMIT 1),'Dakar','dev'||g||'@example.test' FROM generate_series(1,12) AS s(g) WHERE EXISTS (SELECT 1 FROM "users" WHERE "email"='fixture.awa@cpi.sn') ON CONFLICT DO NOTHING`,
		`INSERT INTO "prospect_journeys" ("id","prospectId","projet","statut","createdAt","updatedAt","phase2Status","enrollmentMethod","enrollmentCapturedAt","enrollmentCapturedById") SELECT 'dev-journey-'||row_number() over (order by p."id"),p."id",p."projet",p."statut",p."createdAt",now(),'METHOD_OBTAINED'::"Phase2Status",'PLATFORM'::"EnrollmentMethod",now(),(SELECT "id" FROM "users" WHERE "email"='fixture.awa@cpi.sn') FROM "prospects" p WHERE p."id" LIKE 'dev-prospect-%' ON CONFLICT ("prospectId","projet") DO NOTHING`,
		`INSERT INTO "call_attempts" ("id","prospectId","performedById","outcome","method","clientCreatedAt","createdAt","fonctionnaire","engagementEnCours") SELECT 'dev-call-'||row_number() over (order by p."id"),p."id",(SELECT "id" FROM "users" WHERE "email"='fixture.awa@cpi.sn'),'METHOD_OBTAINED'::"CallOutcome",'PLATFORM'::"EnrollmentMethod",now()-interval '2 days',now()-interval '2 days',true,true FROM "prospects" p WHERE p."id" LIKE 'dev-prospect-%' ON CONFLICT DO NOTHING`,
		`INSERT INTO "rep_call_attempts" ("id","representantId","performedById","outcome","promisedProspects","clientCreatedAt","createdAt") SELECT 'dev-rep-call-001','dev-rep-001',(SELECT "id" FROM "users" WHERE "email"='fixture.awa@cpi.sn'),'PROSPECTS_PROMISED'::"RepCallOutcome",3,now(),now() WHERE EXISTS (SELECT 1 FROM "representants" WHERE "id"='dev-rep-001') ON CONFLICT DO NOTHING`,
		`INSERT INTO "bank_cases" ("id","reference","referenceKey","prospectId","customerName","customerPhoneE164","processingBankId","currentStageId","createdById","updatedAt") SELECT 'dev-bank-case-001','DEV-BANK-001','DEV-BANK-001',p."id",p."prenom"||' '||p."nom",p."phoneE164",(SELECT "id" FROM "banques" LIMIT 1),(SELECT "id" FROM "bank_case_stages" WHERE "code"='A_TRAITER' LIMIT 1),(SELECT "id" FROM "users" WHERE "email"='fixture.banque@cpi.sn'),now() FROM "prospects" p ORDER BY p."id" LIMIT 1 ON CONFLICT DO NOTHING`,
		`INSERT INTO "bank_case_transitions" ("id","caseId","toStageId","performedById","createdAt") SELECT 'dev-transition-001','dev-bank-case-001',"currentStageId",(SELECT "id" FROM "users" WHERE "email"='fixture.banque@cpi.sn'),now() FROM "bank_cases" WHERE "id"='dev-bank-case-001' ON CONFLICT DO NOTHING`,
		`INSERT INTO "visites" ("id","reference","visitedAt","visitorName","phoneE164","entrepriseId","objetId","directionId","destinataireId","createdById","updatedAt") SELECT 'dev-visite-001','DEV-VISITE-001',now()-interval '1 day','Visiteur démonstration','+221770009099',(SELECT "id" FROM "visite_entreprises" LIMIT 1),(SELECT "id" FROM "visite_objets" LIMIT 1),(SELECT "id" FROM "visite_directions" LIMIT 1),(SELECT "id" FROM "visite_destinataires" LIMIT 1),(SELECT "id" FROM "users" WHERE "email"='fixture.accueil@cpi.sn'),now() ON CONFLICT DO NOTHING`,
		`INSERT INTO "inscriptions_plateforme" ("id","projet","identifiantDistant","nom","prenom","statutDistant","prospectId","chargeUtile","dernierTirageAt","updatedAt") SELECT 'dev-inscription-001','CHUES'::"Projet",'DEV-001','Diallo','Mariama','soumis',p."id",'{}'::jsonb,now(),now() FROM "prospects" p ORDER BY p."id" LIMIT 1 ON CONFLICT DO NOTHING`,
		`INSERT INTO "scheduled_callbacks" ("id","prospectId","assignedToId","scheduledAt","comment","sourceAttemptId","updatedAt") SELECT 'dev-callback-001',a."prospectId",a."performedById",now()+interval '2 days','Rappeler',a."id",now() FROM "call_attempts" a ORDER BY a."id" LIMIT 1 ON CONFLICT DO NOTHING`,
		`INSERT INTO "agent_activity_slots" ("userId","slot","firstSeenAt","lastSeenAt","activeSeconds") SELECT "id",date_trunc('hour',now()),now()-interval '1 hour',now()-interval '50 minutes',600 FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "agent_heartbeats" ("userId","lastPullAt","lastPushAt","pendingOps","appVersion","updatedAt") SELECT "id",now(),now(),1,'dev-factory',now() FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "device_tokens" ("id","userId","token","platform","appVersion","updatedAt") SELECT 'dev-token-001',"id",'dev-token','WEB'::"DevicePlatform",'2.0.0',now() FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "dashboard_layouts" ("userId","ecran","layout","updatedAt") SELECT "id",'dev-factory','{}'::jsonb,now() FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "app_settings" ("key","value","updatedById","updatedAt") SELECT 'dev.factory','true',"id",now() FROM "users" WHERE "email"='admin@cpi.sn' ON CONFLICT ("key") DO UPDATE SET "value"=EXCLUDED."value"`,
		`INSERT INTO "audit_logs" ("id","userId","action","entity","entityId","after") SELECT 'dev-audit-001',"id",'CREATE','prospects','dev-prospect-001','{}'::jsonb FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "import_jobs" ("id","kind","status","mode","requestedById","fileName","fileBytes","storagePath","expiresAt","updatedAt") SELECT 'dev-import-001','PROSPECTS'::"ImportKind",'succeeded'::"ImportStatus",'APPLY'::"ImportMode","id",'demo.csv',1024,'dev/demo.csv',now()+interval '30 days',now() FROM "users" WHERE "email"='admin@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "lots_export" ("id","name","cible","projet","filters","itemCount","createdById") SELECT 'dev-lot-001','Lot démonstration','PROSPECTS'::"LotExportCible",'CHUES'::"Projet",'{}'::jsonb,1,"id" FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "lot_export_items" ("lotId","prospectId","position","assigneeId") SELECT 'dev-lot-001',p."id",1,u."id" FROM "prospects" p CROSS JOIN "users" u WHERE u."email"='fixture.fatou@cpi.sn' ORDER BY p."id" LIMIT 1 ON CONFLICT DO NOTHING`,
		`INSERT INTO "notification_templates" ("id","name","titleTemplate","bodyTemplate","createdById","updatedAt") SELECT 'dev-template-001','Factory','Données prêtes','La base de démonstration est prête.',"id",now() FROM "users" WHERE "email"='admin@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "notifications" ("id","title","body","createdById","updatedAt") SELECT 'dev-notification-001','Données de démonstration','La base est prête.',"id",now() FROM "users" WHERE "email"='admin@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "notification_deliveries" ("id","notificationId","userId","status","updatedAt") SELECT 'dev-delivery-001','dev-notification-001',"id",'DELIVERED'::"NotificationDeliveryStatus",now() FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "refresh_tokens" ("id","userId","tokenHash","familyId","expiresAt") SELECT 'dev-refresh-001',"id",'dev-hash','dev-family',now()+interval '30 days' FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "sync_batches" ("userId","idempotency_key","requestHash","status","expiresAt") SELECT "id",'dev-batch-001','dev-hash','COMPLETED'::"BatchStatus",now()+interval '1 day' FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "sync_operations" ("opId","userId","batchKey","entityType","entityId","result") SELECT 'dev-op-001',"id",'dev-batch-001','prospect','dev-prospect-001','APPLIED'::"OperationResult" FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "references_bancaires" ("projet","annee","dernier") VALUES ('CHUES'::"Projet",2026,12),('GRAND_PUBLIC'::"Projet",2026,8) ON CONFLICT ("projet","annee") DO NOTHING`,
		`INSERT INTO "courriels" ("id","type","sujet","destinataires","objetType","objetId","html","texte","statut") VALUES ('dev-email-001','NOTIFICATION','Démonstration',ARRAY['fixture.awa@cpi.sn'],'prospect','dev-prospect-001','<p>Demo</p>','Demo','ENVOYE') ON CONFLICT DO NOTHING`,
		`INSERT INTO "app_setting_changes" ("id","key","oldValue","newValue","changedById") SELECT 'dev-setting-change-001','dev.factory','false','true',"id" FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "android_releases" ("versionCode","versionName","fileName","fileSize","sha256","signerSha256","publishedById","notes") SELECT 9001,'9.0.1','demo.apk',1024,'dev-sha256','dev-signer-sha256',"id",'Version de démonstration' FROM "users" WHERE "email"='fixture.direction@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "device_call_detections" ("id","performedById","representantId","prospectId","deviceCallType","deviceCallDurationSeconds","deviceCallAt","detectedAt") SELECT 'dev-device-call-001',u."id",r."id",p."id",'OUTGOING',90,now()-interval '1 hour',now() FROM "users" u CROSS JOIN "representants" r CROSS JOIN "prospects" p WHERE u."email"='fixture.awa@cpi.sn' ORDER BY p."id" LIMIT 1 ON CONFLICT DO NOTHING`,
		`INSERT INTO "client_creation_requests" ("id","nom","prenom","phoneE164","note","banqueId","requestedById","updatedAt") SELECT 'dev-client-request-001','Ndiaye','Aïssatou','+221770008001','Demande de démonstration',(SELECT "id" FROM "banques" LIMIT 1),"id",now() FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "ouvertures_fiche" ("id","openedById","prospectId","openedAt","draft","updatedAt") SELECT 'dev-ouverture-001',u."id",p."id",now()-interval '20 minutes','{}'::jsonb,now() FROM "users" u CROSS JOIN "prospects" p WHERE u."email"='fixture.awa@cpi.sn' ORDER BY p."id" LIMIT 1 ON CONFLICT DO NOTHING`,
		`INSERT INTO "prospect_conversions" ("id","journeyId","offerId","paymentMode","amountXof","confirmedById") SELECT 'dev-conversion-001',j."id",(SELECT "id" FROM "offers" LIMIT 1),'COMPTANT'::"PaymentMode",150000,u."id" FROM "prospect_journeys" j CROSS JOIN "users" u WHERE u."email"='fixture.superviseur@cpi.sn' ORDER BY j."id" LIMIT 1 ON CONFLICT DO NOTHING`,
		`INSERT INTO "segment_changes" ("id","prospectId","fromSegment","toSegment","fromBanqueId","toBanqueId","fromSyndicatId","toSyndicatId","reason","changedById","source") SELECT 'dev-segment-change-001',p."id",'BDD1'::"BddSegment",'BDD2'::"BddSegment",b."id",b."id",s."id",s."id",'Répartition initiale',u."id",'WEB'::"ChangeSource" FROM "banques" b CROSS JOIN "syndicats" s CROSS JOIN "users" u CROSS JOIN "prospects" p WHERE u."email"='fixture.superviseur@cpi.sn' ORDER BY p."id" LIMIT 1 ON CONFLICT DO NOTHING`,
		`INSERT INTO "representant_comments" ("id","representantId","authorId","body","clientCreatedAt") SELECT 'dev-representant-comment-001','dev-rep-001',"id",'Contact établi pendant la démonstration.',now() FROM "users" WHERE "email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "representant_relation_changes" ("id","representantId","fromStatus","toStatus","reason","changedById","source") SELECT 'dev-relation-change-001','dev-rep-001','INCONNU'::"RepresentantRelation",'AMBASSADEUR'::"RepresentantRelation",'Qualification initiale',"id",'WEB'::"ChangeSource" FROM "users" WHERE "email"='fixture.superviseur@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "representant_suggestions" ("id","sourceRepresentantId","suggestedName","suggestedPhoneE164","note","suggestedById","sourceAttemptId","clientCreatedAt") SELECT 'dev-suggestion-001','dev-rep-001','Moussa Fall','+221770009002','Recommandation de démonstration',u."id",'dev-rep-call-001',now() FROM "users" u WHERE u."email"='fixture.awa@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "lot_export_reaffectations" ("id","lotId","toAssigneeId","fiches","performedById","positions") SELECT 'dev-reaffectation-001','dev-lot-001',u."id",1,u."id",ARRAY[1] FROM "users" u WHERE u."email"='fixture.fatou@cpi.sn' ON CONFLICT DO NOTHING`,
		`INSERT INTO "visite_import_changes" ("id","importJobId","sheet","rowNumber","kind","reference","visiteId","label","fields") SELECT 'dev-visite-import-change-001','dev-import-001','Visites',2,'CREATE'::"VisiteImportChangeKind",'DEV-VISITE-001','dev-visite-001','Visite de démonstration','{}'::jsonb ON CONFLICT DO NOTHING`,
	}
	for i, statement := range statements {
		if _, err := tx.Exec(ctx, statement); err != nil {
			return fmt.Errorf("factory statement %d (%s): %w", i+1, statement, err)
		}
	}
	return nil
}
