swagger_parser:
  schema_path: ../api/openapi.json
  output_directory: lib/generated
  json_serializer: json_serializable
  root_client: false
  export_file: false
  put_in_folder: false
  mark_files_as_generated: true
  field_parsers:
    - apply_to_type: "DateTime"
      parser_name: "LocalDateTimeConverter"
      parser_absolute_path: "package:gnawalma/json_converters.dart"
    - apply_to_type: "DateTime?"
      parser_name: "NullableLocalDateTimeConverter"
      parser_absolute_path: "package:gnawalma/json_converters.dart"
